### ISSUE TITLE
How to use it with more than one dongle?

### ISSUE THREAD

**Issue by varnav** [aerospaceresearch/CalibrateSDR#15]
Unfortunately there is zero documentation on any command line parameters.

I have two dongles, how to use this program?

**Comment by jyrj** [comment]
The program needs to be run parallelly if you want to test it with 2 dongles simultaneously.
Just give the `-rd` parameter accordingly. You can choose the device number.

`~$ python cali.py -h` will give you the available parameters.

For extensive documentation on specific signals:

https://aerospaceresearch.net/?page_id=2111 - **DAB+**
https://aerospaceresearch.net/?p=2347 - **DVB-T**
https://aerospaceresearch.net/?p=2349 - **GSM (2G)**

Support for LTE (4G) is under development. Documentation/ Wiki for overall usage will be created too.
