### ISSUE TITLE
Throwing AttributeError while running the cali.py in Linux based OS

### ISSUE THREAD

**Issue by jyrj** [aerospaceresearch/CalibrateSDR#3]
Getting ```AttributeError: python: undefined symbol: rtlsdr_get_device_count``` while running cali.py, (even after installing using setup.py). Tried on different Python versions (3.6, 3.8 and 3.9), still it persists. 
This seems to be an issue pertaining with Linux-based OS only. Working in WIndows will not throw the issue. Below attached is the command-line picture.

You can simply reproduce the issue just using `import rtlsdr` statements (even though it has been installed).

![image](https://user-images.githubusercontent.com/54764778/111408238-fd076b80-86fa-11eb-9c4f-c0db9b9104a2.png)

UPDATE: I have worked on the issue, and will update the Readme for troubleshooting guidance

**Comment by Ayush-SR** [comment]
Try updating your rtlsdr library. It worked for me.
`sudo apt-get install librtlsdr-dev`
